In [2]:
import sys
import os
import numpy as np
import flopy

In [3]:
h1 = 100
h2 = 90
Nlay = 10 
N = 101 
L = 400.0 
H = 50.0 
k = 1.0

In [4]:
bot = np.linspace(-H/Nlay,-H,Nlay) 


In [5]:
print(bot)

[ -5. -10. -15. -20. -25. -30. -35. -40. -45. -50.]


In [22]:
print(np.linspace(0,0,2))
print(np.linspace(0,1,2))
laycon = np.linspace(0,0,2)
print(laycon)

[ 0.  0.]
[ 0.  1.]
[ 0.  0.]


In [20]:
#help(np.array)
tt = np.array([100., 1., 1000.])
print(tt)

[  100.     1.  1000.]


In [25]:
#help(flopy.modflow.ModflowOc)
print(help(flopy.modflow.ModflowRch))

Help on class ModflowRch in module flopy.modflow.mfrch:

class ModflowRch(flopy.pakbase.Package)
 |  MODFLOW Recharge Package Class.
 |  
 |  Parameters
 |  ----------
 |  model : model object
 |      The model object (of type :class:`flopy.modflow.mf.Modflow`) to which
 |      this package will be added.
 |  ipakcb : int
 |      A flag that is used to determine if cell-by-cell budget data should be
 |      saved. If ipakcb is non-zero cell-by-cell budget data will be saved.
 |      (default is 0).
 |  nrchop : int
 |      is the recharge option code. 
 |      1: Recharge to top grid layer only
 |      2: Recharge to layer defined in irch
 |      3: Recharge to highest active cell (default is 3).
 |  rech : float or array of floats (nrow, ncol)
 |      is the recharge flux. (default is 1.e-3).
 |  irch : int or array of ints (nrow, ncol)
 |      is the layer to which recharge is applied in each vertical
 |      column (only used when nrchop=2). (default is 0).
 |  extension : string
 |

In [28]:
nlay = 1
nrow = 27
ncol = 13

nlay = 1
nrow = 1
ncol = 11

ibound = np.ones((nlay, nrow, ncol))
ibound[0, 0, :10] = -1
ibound[0, 0, 90:] = -1
print(ibound)

[[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  

In [29]:
nlay = 20
nrow = 1
ncol = 100

ibound = np.ones((nlay, nrow, ncol))
ibound[0, 0, :10] = -1
ibound[0, 0, 90:] = -1
print(ibound)



[[[-1. -1. -1. ..., -1. -1. -1.]]

 [[ 1.  1.  1. ...,  1.  1.  1.]]

 [[ 1.  1.  1. ...,  1.  1.  1.]]

 ..., 
 [[ 1.  1.  1. ...,  1.  1.  1.]]

 [[ 1.  1.  1. ...,  1.  1.  1.]]

 [[ 1.  1.  1. ...,  1.  1.  1.]]]
